clockworklabs/spacetimedb-typescript-sdk

src/identity.ts, src/index.ts, src/spacetimedb.ts, tests/spacetimedb_client.test.ts, tests/types/create_player_reducer.ts
*Describe what has been changed, any new features or bug fixes*
UInt8Array -> Identity
Reducer callbacks now get a ReducerEvent instead of just caller and status
- [X ] This is an API breaking change to the SDK
Projects using this SDK will need to:
- update their references to identities from UInt8Arrays to Identity
- update any reducer callbacks to take a ReducerEvent as the first argument
https://github.com/clockworklabs/SpacetimeDB/pull/94
=> Change Identity from UInt8Array to Identity to match other SDKs

src/binary_writer.ts
Typescript SDK was adding an extra 0 to the end of the buffer, this causes a bug in C# module implementation which actually validates the length
=> Fix BSATN serialization for c# module support

src/spacetimedb.ts
At the moment when we authenticate with the short-lived token we also get the short lived token back. In order to not give it back to the application let's just ignore the identity message token if we already got one
=> Fix auth in the browser

src/identity.ts, src/serializer.ts, src/spacetimedb.ts
After the format of keeping the identity on the server was changed we have to update how we serialize and deserialize Identity values
=> Fix Identity serialization/deserialization

src/database_table.ts, tests/spacetimedb_client.test.ts
This PR fixes the `with` method available on database tables, which allows to call methods on the table with multiple clients
=> Fix type returned by DatabaseTable.with method

package.json
`protobufjs` was defined twice in the package.json inside dependencies and devDependencies which causes bun (javascript runtime and bundler) to fail to install the dependencies.
```bash
bun install v0.8.1 (16b4bf34)
error: Duplicate dependency: "protobufjs" specified in package.json
"protobufjs": "^7.2.4",
^
/home/jk/pr/spacetimedb-typescript-sdk/package.json:38:5 960
note: "protobufjs" originally specified here
"protobufjs": "^7.2.4",
```
Since it's used during runtime (in client_api.ts) it should be in the dependencies.
N/A
=> Remove `protobufjs` from devDependencies

src/client_db.ts, src/database_table.ts, src/global.ts, src/index.ts, src/logger.ts, src/message_types.ts, src/spacetimedb.ts, src/utils.ts, tests/spacetimedb_client.test.ts
- Updated package structure. Separated concerns into more readable files.
- Updated out-of-date comments for method tooltips
- Added a new error handling system to create more transparent issues surface
- Added new logging system, new system can be expanded upon. Would be great to have a full logging system, as well as a variable to disable verbose logging in the future
- [] This is **NOT** an API breaking change to the SDK
- Initially it was thought it may break the API, however the changes required were not breaking.
=> Cleaned up code and added better error handling and responses for invalid tables

src/reducer.ts, src/spacetimedb.ts
Related to this issues, clockworklabs/spacetimedb-typescript-sdk/issues/31
This commit change the way the table and reducer are registered to prevent an error message like `Could not find class "Person", you need to register it with SpacetimeDBClient.registerTable() first` to happen.
Some Typescript based project change the name of the classes when beging converted into javaScript. This behavior prevent the Tables and Reducer to be registered with the right name.
I used the name who are found in the auto generated TypeScript code.
reducer.reducerName for the reducer and table.tableName for the tables
=> Fix issue where some Typescript based project transpiler might mangle the table or Reducer

examples/quickstart/client/package-lock.json, examples/quickstart/server/Cargo.lock, package-lock.json, package.json, src/spacetimedb.ts, yarn.lock
Uses [brotli.js](https://www.npmjs.com/package/brotli) to decompress incoming binary messages before Protobuf deserializing.
- https://github.com/clockworklabs/SpacetimeDB/pull/1026
=> brotli-decompress received binary websocket messages

package.json
Bump the version number to 0.10.0 in coordination with the release.
I don't know, but corresponding SpacetimeDB PR: https://github.com/clockworklabs/SpacetimeDB/pull/1352
=> Bump version to 0.10.0

package.json, pnpm-lock.yaml, src/client_db.ts, src/spacetimedb.ts, tsconfig.json, tsup.config.ts
- Builds everything into one file: index.js
- All types are built into index.d.ts
- Provides a `/min` folder with terser-minified index.js, which is automatically picked up by smart bundlers for production build, giving smaller output overall
- Use browser build of `brotli`, bringing bundle size down to 75KB min+brotli 🎉
- `publint` tested
Tests are breaking because jest doesn't work in ESModules without extreme hacks, will be addressed in a later PR
=> modernize: tsup

.npmignore, examples/quickstart/client/src/App.test.tsx, jest.config.js, package.json, pnpm-lock.yaml, tests/algebraic_value.test.ts, tests/spacetimedb_client.test.ts, vitest.config.ts
jest doesn't work in ESM only workspaces, hence we're using vitest(also much faster)
=> modernize: jest to vitest

packages/sdk/package.json, packages/sdk/src/events.ts, packages/sdk/src/spacetimedb.ts, packages/sdk/src/table.ts, pnpm-lock.yaml
Gets rid of `events` package which does too much. We need only on, off and emit events, which are easily done in our own code
=> modernize: in-house EventEmitter

package.json, packages/sdk/package.json
Removes conditional imports, now it relies only on dist/index.js. This is to avoid ambiguity going from dev mode to prod mode, and any monkey patching someone could've done
=> modernize: Single output

package.json, packages/sdk/package.json
Makes sure the SDK isn't used before v18
=> modernize: Engines field

src/websocket_decompress_adapter.ts
@Dynrothe described an issue where rows were not being deleted on FireFox and created a [minimal reproduction](https://github.com/Dynrothe/spacetimedb-ts-bug-demo). 
This was discovered to be due to out of order processing of ws messages which can be seen [here](https://github.com/tcardlab/Dynnys-STDB-bug-demo/tree/investigation):
<Details>
<Summary><strong>Code Catching Out of Order Messages:</strong></Summary>
This code will log the received messages first ("msg n"), then the log them as they resolve ("from msg n").
</Details>
<Details>
<Summary><strong>FireFox Error:</strong></Summary>
Messages are received in order in accordance with TCP, but resolved out of order.<br/>
Here you can see an out of oder message (38) is failing to delete a row that has not been inserted yet (37).<br/> …
=> Fix: Synchronous WS Processing

packages/sdk/src/websocket_decompress_adapter.ts
This tells webpack to ignore undici dynamic import so it doesn't trip. I won't prevent other bundlers though, so this is only a hacky solution just for Webpack 4 and Create-React-App
=> modernize: webpackIgnore undici

packages/sdk/package.json, packages/sdk/src/websocket_decompress_adapter.ts, packages/sdk/tsconfig.json, tsup.config.ts
Current dynamic import of undici is for nodeJS usage only, but because of the dynamic import of `undici`, it fills up the logs with `node:http` warnings. They are harmless, but in some cases it fills up user's final build with an extra module containing undici's source. It is never imported, but our duty as library authors is to keep the build slim and non-problematic in every way.
Hence this PR splits up the build into browser build and regular build. Browser build will be used first and foremost by any bundlers(including Webpack 1+), the regular build with undici dynamic import will be used by NodeJS/bun/Deno/any non-browser environment. 
This allows us to remove `webpackIgnore`, simply because webpack will never encounter the dynamic import
=> modernize: Conditional browser build

.changeset/beige-paws-repair.md, packages/sdk/src/spacetimedb.ts
Closes #67
Allows autocomplete in .on and .off methods
=> fix: .on and .off types

.changeset/dull-mangos-appear.md, packages/sdk/src/db_connection_impl.ts, packages/sdk/src/websocket_decompress_adapter.ts, packages/test-app/package.json, packages/test-app/server/src/lib.rs, packages/test-app/src/App.tsx, packages/test-app/src/module_bindings/create_player_reducer.ts, packages/test-app/src/module_bindings/index.ts, packages/test-app/src/module_bindings/player_table.ts, packages/test-app/src/module_bindings/player_type.ts, packages/test-app/src/module_bindings/point_type.ts, packages/test-app/src/module_bindings/user_table.ts, packages/test-app/src/module_bindings/user_type.ts
Fixes a few trivial things
- WebSocket message handling was returning the wrong ArrayBuffer
- db_connection_impl wasn't importing Buffer causing errors in browser
- onConnect was providing wrong arguments, fixes that
- test-app lib.rs now uses public tables
Rest of changes are codegen
=> fix: websocket message handling, Buffer, onConnect

examples/quickstart/src/App.tsx, packages/sdk/README.md, packages/sdk/src/db_connection_builder.ts, packages/test-app/src/App.tsx
`withCredentials` was designed for our old auth model, where tokens were always issued by the SpacetimeDB host alongside an `Identity`, and therefore the bearer always knew their `Identity`.
In our new auth model,
a client may have a valid auth-able JWT but not know what `Identity` it will result in, as the `Identity` is computed based on the hash of some of the token's contents, and this hashing algorithm is not included in our client SDKs. As such, this PR revises `withCredentials` to `withToken`, which just accepts the token.
See description.
N/a
Completely untested.
=> Amend `withCredentials` to `withToken`

packages/sdk/src/db_context.ts
TypeScript analogue to https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/pull/211 and https://github.com/clockworklabs/SpacetimeDB/pull/2109
Additive-only
Nope!
=> Add `subscribeToAllTables` method

packages/sdk/src/db_connection_impl.ts, packages/sdk/src/message_types.ts
Now emitting UnknownTransaction if reducer name is empty string or the reducer args are not parseable. This is in line with @gefjon's specification.
Technically a breaking change as we are handling even emitting differently.
None.
It is not possible to test with the automated tests given the state of the repo and SpacetimeDB, but we will test once everything has merged.
=> Now emitting UnknownTransaction

packages/sdk/src/websocket_decompress_adapter.ts
Switches to Bearer authentication, which is the more proper auth schema to use with tokens.
- https://github.com/clockworklabs/SpacetimeDB/pull/2181
=> Switch to Bearer auth

packages/sdk/src/algebraic_type.ts
This fixes a circular import or circular definition problem that we don't fully understand.
_Write instructions for a test that you performed for this PR_
=> Import timestamp and duration by file, not from root

packages/sdk/README.md, packages/sdk/package.json, packages/test-app/package.json
Bumps version numbers to 1.0.0. I'm not confident that I haven't missed any.
It's not obvious to me that this is the "correct" way to update these versions, since I'm unfamiliar with the changeset docs.
Not breaking.
https://github.com/clockworklabs/SpacetimeDB/pull/2283
=> Bump version to 1.0.0

packages/sdk/package.json
We're *pretty* sure that this will ship out the 1.0.0 release. Our last release was accidentally shipped out as 1.0.0 so this release is 1.0.1 which is compatible with 1.0.0!
This contains a lot of breaking changes from the previous release but this is known.
Requires tag `v1.0.0`
=> Bump version for release

packages/sdk/src/websocket_decompress_adapter.ts
This fixes a bug that made parsing large messages fail if the connection was created without an existing auth token.
I tested manually using a version of the quickstart that sends very large messages and ignores the auth token in local storage.
=> Set other url params even if we dont have an authToken.

packages/sdk/src/utils.ts
This reverses the byte order when hex encoding/decoding identities or connection ids.
Technically changes `toHexString`, but this is a bug fix.
I relied on manual testing to make sure that the clients Identity and ConnectionId matched what the server expected.
Testing of our binary encoding and decoding is very sparse right now.
=> Reverse byte order when converting to/from hex strings

packages/sdk/package.json
There are no new PRs since the last release, but we still need to bump the minor version.
**Merging this PR will cause a new package version to be published**
No breaking changes
https://github.com/clockworklabs/SpacetimeDB/pull/2566
This just bumps the version. No new changes have merged since 1.0.3, so no new testing required.
=> Release 1.1.0

examples/quickstart-chat/src/App.tsx
Updates the quickstart to put all of the queries in a single subscription.
I ran the quickstart app locally.
=> Subscribe to all the subscriptions together in the quickstart example.

examples/quickstart-chat/src/index.css, packages/sdk/src/db_connection_impl.ts, packages/sdk/src/websocket_decompress_adapter.ts
Currently due to how URL's are handled in the sdk you cannot host a spacetimedb at a path on domain. Such as `wss://pixelz.games/api`. This is inconvenient since for web dev and spacetimedb you will have a minimum of 2 different servers running. One that handles at least static files and spacetimedb. The common web convention for stuff like this is just configure nginx to reroute traffic from a `/api' or '/service' path. This PR makes that possible to do.
This has no external effect and should cause no breaking changes.
There are no external PR's to this.
Automated testing and built & compiled these changes into a change for my project.
A simple test is just have nginx handle spacetimedb at a pathname & not a pathname. If it works in both scenarios this code works as intended.
Basic …
=> Fix so spacetimedb can be hosted with a pathname

packages/sdk/src/algebraic_type.ts, packages/sdk/tests/algebraic_value.test.ts
Fixes a bug with option serialization where values that evaluate to false were being treated as `None`.
There are a couple basic unit tests for falsy values.
=> Handle falsy option values

packages/sdk/package.json
Bump version to 1.2.0.
Merging this PR will **release** this package version.
No breaking changes.
I don't think this version bump itself requires anything.
CI only
=> Release 1.2.0

packages/sdk/package.json
We have merged two bugfixes (#194 and #195), and we'd like to release these.
No breaking changes
None
See those PRs. This is just a version bump.
=> Bump version to 1.2.1 for release

packages/sdk/src/websocket_decompress_adapter.ts
Connection to an instance fails with React Native, this is the error:
[Error: Exception in HostFunction: Expected argument 0 of method "connect" to be a string, but got an object]
This error was caused by React Native implementation of Websocket, in our SDK we use an instance of Url to pass all the parameters like token, compression, etc. but React Native requires this parameter to be a string and not Url | **string.**
=> Use toString() instead of an instance of Url when opening the websocket

packages/sdk/package.json
Bump version numbers to 1.2.2. Merging this PR will release this version (because we don't have any outstanding changesets).
Includes these commits:
```
e2f0427 Use toString() instead of an instance of Url when opening the websocket connection
d808e41 Improve performance of row ids (#180)
fdd4618 CI - Test that quickstart-chat builds (#197)
6ea0c6f Require a minimum code gen version (#186)
```
No breaking changes
None
None
=> Release 1.2.2
