src/algebraic_value.ts
src/spacetimedb.ts

also:
- remove identity from credentials (not needed to log in)
- add auth token to "connected" event

Fix identity deserialize

---

src/spacetimedb.ts
tests/spacetimedb_client.test.ts
tests/types/player.ts

We support primaryKey fields now, thus we can also perform an update operation on the client by utilizing the primaryKey

Add support for update

---

.github/pull_request_template.md

Added PR template, you can see what it looks like here: https://github.com/clockworklabs/SpacetimeDBCSharpSDK/blob/jdetter/default-pull-request-template/.github/pull_request_template.md

Created PR Template

---

src/spacetimedb.ts

*Describe what has been changed, any new features or bug fixes*

Fix reducer event argument being undefined if the reducer fails.

---

examples/quickstart/client/src/module_bindings/message.ts
examples/quickstart/client/src/module_bindings/send_message_reducer.ts
examples/quickstart/client/src/module_bindings/set_name_reducer.ts
examples/quickstart/client/src/module_bindings/user.ts
package-lock.json
src/address.ts
src/client_api.ts
src/identity.ts
src/index.ts
src/spacetimedb.ts

*Describe what has been changed, any new features or bug fixes*
`onConnect` callbacks take an additional argument, the client's `Address`.
https://github.com/clockworklabs/SpacetimeDB/pull/299

Client address support for TypeScript SDK

---

package.json

Bump to 0.8.2

---

.github/workflows/cr.yml
.github/workflows/lint.yml

modernize: Split lint and test GH actions

---

.github/workflows/release.yml

fix: Release action

---

packages/sdk/package.json

Changesets takes care of GH releases

fix: Remove registry

---

DEVELOP.md

docs: Publishing and release

---

.changeset/config.json
package.json
pnpm-lock.yaml

This makes our changelog point to PRs, mention contributors and overall a bit better github integration

feat: changelog-github

---

.changeset/pre.json
.changeset/smart-dogs-listen.md

Enter prerelease mode

---

.changeset/two-garlics-sin.md

Add changeset for #109

---

.changeset/pre.json
packages/sdk/README.md

Update readme for next.0

---

packages/sdk/src/db_connection_impl.ts
packages/sdk/src/websocket_decompress_adapter.ts

Companion PR for the http api glowup.
- https://github.com/clockworklabs/SpacetimeDB/pull/2225

Adjust http api usage for glowup

---

.github/workflows/test.yml

Disables the broken integration test.
Automated testing should now pass.

Disable SpacetimeDB integration test for now

---

packages/sdk/src/db_connection_impl.ts
packages/sdk/src/subscription_builder_impl.ts

This fixes some issues with ending subscriptions, either via unsubscribe or errors.
This was tested manually, but we should definitely add unit tests covering this in the future.

Fix some subscription lifecycle issues.

---

packages/sdk/package.json

This release only contains bug fixes. Includes these PRs:
- https://github.com/clockworklabs/spacetimedb-typescript-sdk/pull/158
- https://github.com/clockworklabs/spacetimedb-typescript-sdk/pull/161
No breaking changes.
None
_Write instructions for a test that you performed for this PR_

Version upgrade to 1.0.3

---

LICENSE

- I've added an Apache2 license which is consistent with our other SDK repositories.
_Write instructions for a test that you performed for this PR_
- NA - documentation change

License this repo as Apache2

---

.github/workflows/lint.yml
examples/quickstart-chat/src/.gitattributes
examples/quickstart-chat/src/index.css
packages/test-app/src/.gitattributes

Fixes a file that wasn't formatted, and adds the lint check to PRs.
This also includes from `.gitattributes` changes to hide generated files from diffs.

Run lint for PRs.

---

packages/sdk/src/websocket_decompress_adapter.ts

Similar to the fixes in https://github.com/clockworklabs/spacetimedb-typescript-sdk/pull/192 and https://github.com/clockworklabs/spacetimedb-typescript-sdk/pull/193, this fixes a bug introduced in https://github.com/clockworklabs/spacetimedb-typescript-sdk/pull/183.
Previously, we were throwing away the temporary token, because creating `databaseUrl` with an absolute path throws away any search params.

Use the temporary auth token.
